# Generated by Django 3.2.8 on 2021-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
